changelog:
  exclude:
    labels:
      - package::documentation
      - package::addition
      - package::breakage
  categories:
    - title: Added
      labels:
        - enhancement
    - title: Changed
      labels:
        - refactor
    - title: Fixed
      labels:
        - bug
