name: Build and release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+ # semver
      - '!dev-build' # not dev-build

jobs:
  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/build_artifacts.yml
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Downloads artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin
      - name: Create pre-release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: bin/*/uad-ng-*
          generate_release_notes: true
